#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dictionary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOFdict")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertnadzór(nadzór instance);
    partial void Updatenadzór(nadzór instance);
    partial void Deletenadzór(nadzór instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DictionaryCS"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<main> mains
		{
			get
			{
				return this.GetTable<main>();
			}
		}
		
		public System.Data.Linq.Table<czesci_mowy> czesci_mowies
		{
			get
			{
				return this.GetTable<czesci_mowy>();
			}
		}
		
		public System.Data.Linq.Table<nadzór> nadzórs
		{
			get
			{
				return this.GetTable<nadzór>();
			}
		}
		
		public System.Data.Linq.Table<rodzaj> rodzaj
		{
			get
			{
				return this.GetTable<rodzaj>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.main")]
	public partial class main
	{
		
		private int _ID;
		
		private string _EngItem;
		
		private string _PolItem;
		
		private System.Nullable<int> _PartOfSpeach;
		
		private System.Nullable<System.DateTime> _LastModification;
		
		private System.Nullable<System.DateTime> _FirstInput;
		
		private string _Abbreviation;
		
		private System.Nullable<int> _Branch;
		
		private System.Nullable<int> _TermType;
		
		private string _PolItemDef;
		
		private string _EngItemDef;
		
		private System.Nullable<int> _Synonyms;
		
		private System.Nullable<int> _Antonyms;
		
		private System.Nullable<int> _TermSuperior;
		
		private System.Nullable<int> _TermInferior;
		
		private System.Nullable<int> _TermAssociated;
		
		private System.Nullable<int> _FalseFriendPL;
		
		private System.Nullable<int> _FalseFriendANG;
		
		private System.Nullable<int> _Image;
		
		private System.Nullable<int> _Colocations;
		
		private string _Examples;
		
		private System.Nullable<int> _Occurence;
		
		private string _AdditionalInfo;
		
		public main()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngItem", DbType="NVarChar(50)")]
		public string EngItem
		{
			get
			{
				return this._EngItem;
			}
			set
			{
				if ((this._EngItem != value))
				{
					this._EngItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolItem", DbType="NVarChar(50)")]
		public string PolItem
		{
			get
			{
				return this._PolItem;
			}
			set
			{
				if ((this._PolItem != value))
				{
					this._PolItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartOfSpeach", DbType="Int")]
		public System.Nullable<int> PartOfSpeach
		{
			get
			{
				return this._PartOfSpeach;
			}
			set
			{
				if ((this._PartOfSpeach != value))
				{
					this._PartOfSpeach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModification", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastModification
		{
			get
			{
				return this._LastModification;
			}
			set
			{
				if ((this._LastModification != value))
				{
					this._LastModification = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstInput", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FirstInput
		{
			get
			{
				return this._FirstInput;
			}
			set
			{
				if ((this._FirstInput != value))
				{
					this._FirstInput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abbreviation", DbType="NChar(5)")]
		public string Abbreviation
		{
			get
			{
				return this._Abbreviation;
			}
			set
			{
				if ((this._Abbreviation != value))
				{
					this._Abbreviation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="Int")]
		public System.Nullable<int> Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this._Branch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermType", DbType="Int")]
		public System.Nullable<int> TermType
		{
			get
			{
				return this._TermType;
			}
			set
			{
				if ((this._TermType != value))
				{
					this._TermType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolItemDef", DbType="NVarChar(MAX)")]
		public string PolItemDef
		{
			get
			{
				return this._PolItemDef;
			}
			set
			{
				if ((this._PolItemDef != value))
				{
					this._PolItemDef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngItemDef", DbType="NVarChar(MAX)")]
		public string EngItemDef
		{
			get
			{
				return this._EngItemDef;
			}
			set
			{
				if ((this._EngItemDef != value))
				{
					this._EngItemDef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Synonyms", DbType="Int")]
		public System.Nullable<int> Synonyms
		{
			get
			{
				return this._Synonyms;
			}
			set
			{
				if ((this._Synonyms != value))
				{
					this._Synonyms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Antonyms", DbType="Int")]
		public System.Nullable<int> Antonyms
		{
			get
			{
				return this._Antonyms;
			}
			set
			{
				if ((this._Antonyms != value))
				{
					this._Antonyms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermSuperior", DbType="Int")]
		public System.Nullable<int> TermSuperior
		{
			get
			{
				return this._TermSuperior;
			}
			set
			{
				if ((this._TermSuperior != value))
				{
					this._TermSuperior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermInferior", DbType="Int")]
		public System.Nullable<int> TermInferior
		{
			get
			{
				return this._TermInferior;
			}
			set
			{
				if ((this._TermInferior != value))
				{
					this._TermInferior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermAssociated", DbType="Int")]
		public System.Nullable<int> TermAssociated
		{
			get
			{
				return this._TermAssociated;
			}
			set
			{
				if ((this._TermAssociated != value))
				{
					this._TermAssociated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FalseFriendPL", DbType="Int")]
		public System.Nullable<int> FalseFriendPL
		{
			get
			{
				return this._FalseFriendPL;
			}
			set
			{
				if ((this._FalseFriendPL != value))
				{
					this._FalseFriendPL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FalseFriendANG", DbType="Int")]
		public System.Nullable<int> FalseFriendANG
		{
			get
			{
				return this._FalseFriendANG;
			}
			set
			{
				if ((this._FalseFriendANG != value))
				{
					this._FalseFriendANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Int")]
		public System.Nullable<int> Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colocations", DbType="Int")]
		public System.Nullable<int> Colocations
		{
			get
			{
				return this._Colocations;
			}
			set
			{
				if ((this._Colocations != value))
				{
					this._Colocations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Examples", DbType="NVarChar(MAX)")]
		public string Examples
		{
			get
			{
				return this._Examples;
			}
			set
			{
				if ((this._Examples != value))
				{
					this._Examples = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occurence", DbType="Int")]
		public System.Nullable<int> Occurence
		{
			get
			{
				return this._Occurence;
			}
			set
			{
				if ((this._Occurence != value))
				{
					this._Occurence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfo", DbType="NVarChar(MAX)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this._AdditionalInfo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.czesci_mowy")]
	public partial class czesci_mowy
	{
		
		private int _Identyfikator;
		
		private string _skrot;
		
		private string _pelna;
		
		private string _dodatek;
		
		private string _skrot_en;
		
		public czesci_mowy()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identyfikator", DbType="Int NOT NULL")]
		public int Identyfikator
		{
			get
			{
				return this._Identyfikator;
			}
			set
			{
				if ((this._Identyfikator != value))
				{
					this._Identyfikator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skrot", DbType="NVarChar(255)")]
		public string skrot
		{
			get
			{
				return this._skrot;
			}
			set
			{
				if ((this._skrot != value))
				{
					this._skrot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pelna", DbType="NVarChar(255)")]
		public string pelna
		{
			get
			{
				return this._pelna;
			}
			set
			{
				if ((this._pelna != value))
				{
					this._pelna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dodatek", DbType="NVarChar(255)")]
		public string dodatek
		{
			get
			{
				return this._dodatek;
			}
			set
			{
				if ((this._dodatek != value))
				{
					this._dodatek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skrot_en", DbType="NVarChar(255)")]
		public string skrot_en
		{
			get
			{
				return this._skrot_en;
			}
			set
			{
				if ((this._skrot_en != value))
				{
					this._skrot_en = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nadzór")]
	public partial class nadzór : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _user;
		
		private System.Nullable<int> _RecID;
		
		private string _Politem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnRecIDChanging(System.Nullable<int> value);
    partial void OnRecIDChanged();
    partial void OnPolitemChanging(string value);
    partial void OnPolitemChanged();
    #endregion
		
		public nadzór()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="NVarChar(50)")]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int")]
		public System.Nullable<int> RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this.OnRecIDChanging(value);
					this.SendPropertyChanging();
					this._RecID = value;
					this.SendPropertyChanged("RecID");
					this.OnRecIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Politem", DbType="NVarChar(50)")]
		public string Politem
		{
			get
			{
				return this._Politem;
			}
			set
			{
				if ((this._Politem != value))
				{
					this.OnPolitemChanging(value);
					this.SendPropertyChanging();
					this._Politem = value;
					this.SendPropertyChanged("Politem");
					this.OnPolitemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rodzaj")]
	public partial class rodzaj
	{
		
		private int _ID;
		
		private string _branch;
		
		public rodzaj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch", DbType="NVarChar(255)")]
		public string branch
		{
			get
			{
				return this._branch;
			}
			set
			{
				if ((this._branch != value))
				{
					this._branch = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
